# ===============================
# = DATA SOURCE
# ===============================


spring:
  datasource:
           hikari:   # Set here configurations for the database connection
                    connection-test-query:
           url: 
           username: 
           password: 
           driver-class-name: 
  jpa:
        database-platform: 
        database: 
        show-sql: 
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false

# ======================================
# = Enable SQL Parameter Tracing in Logs
# ======================================
#logging:
#  level:
#    org:
#      hibernate:
#        type: trace
#        SQL: debug
amsi:
  url: http://www.clk-pm.net/AMSIweb/edexweb/esite/leasing.asmx
  username: fasrclk
  password: fasrclk
  portfolio: esite clk
  
yardi:
  endpoint: https://www.yardiasp14.com/42258polinger/Webservices/ItfRentersinsurance.asmx
  username: CLSRRent
  password: CoreLogic123
  serverName: yovhyeqo_live
  databaseName: yovhyeqo_live
  platform: SQL Server
  interfaceEntity: CoreLogic Renters Insurance
  interfaceLicence: MIIBEAYJKwYBBAGCN1gDoIIBATCB/gYKKwYBBAGCN1gDAaCB7zCB7AIDAgABAgJoAQICAIAEAAQQ23OWB9Mvr3tLAnvLm5e9hASByGMz/H5b6mLwEnw9ZXisQk7KrPKdOVt37cGegkYjY9ArPEtkroeFlrRew3Tp+CWFtiyA2tDNx4osvpI2uWaOuKsatS5fGiuoImOhE57hiKFsh8MATTGfFOlXIE0KYbcryGQebHH1c12JyFyCww13Ya4a2nMtJrriyDik/v5yBjSBKlt/jLfPQNJvdFKTpYQJz3ijG4oYtUlhV/nXBfiB05WrNoyZHTZns+59hWWDR9iDkcFJlcvgh2RFwdJTvdt3ZLiqrZKpEQgE




  
