# ===============================
# = DATA SOURCE
# ===============================

spring:
  main:
    web-environment: true

mssql:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jdbcUrl: jdbc:sqlserver://10.214.32.200:1433;databaseName=microservices
    username: weblogin
    password: web10@gin
    remove-abandoned: true
    remove-abandoned-timeout: 120
    log-abandoned: true
    max-active: 50
    default-auto-commit: true
    test-on-borrow: true
    test-on-connect: true
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    validation-query: SELECT 1
    tomcat:
      remove-abandoned: true
      remove-abandoned-timeout: 120
      log-abandoned: true
      default-auto-commit: true
      test-on-connect: true
      test-on-borrow: true
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2008Dialect
    database: SQL_SERVER
    show-sql: true


amsi:
  url: http://www.clk-pm.net/AMSIweb/edexweb/esite/leasing.asmx
  username: fasrclk
  password: fasrclk
  portfolio: esite clk
  
yardi:
  cronExpression: 0 48 15 * * ?
  endpoint: https://www.yardiasp14.com/42258polinger/Webservices/ItfRentersinsurance.asmx
  username: CLSRRent
  password: CoreLogic123
  serverName: yovhyeqo_live
  databaseName: yovhyeqo_live
  platform: SQL Server
  interfaceEntity: CoreLogic Renters Insurance
  interfaceLicence: MIIBEAYJKwYBBAGCN1gDoIIBATCB/gYKKwYBBAGCN1gDAaCB7zCB7AIDAgABAgJoAQICAIAEAAQQ23OWB9Mvr3tLAnvLm5e9hASByGMz/H5b6mLwEnw9ZXisQk7KrPKdOVt37cGegkYjY9ArPEtkroeFlrRew3Tp+CWFtiyA2tDNx4osvpI2uWaOuKsatS5fGiuoImOhE57hiKFsh8MATTGfFOlXIE0KYbcryGQebHH1c12JyFyCww13Ya4a2nMtJrriyDik/v5yBjSBKlt/jLfPQNJvdFKTpYQJz3ijG4oYtUlhV/nXBfiB05WrNoyZHTZns+59hWWDR9iDkcFJlcvgh2RFwdJTvdt3ZLiqrZKpEQgE




  
